
# export PYTHONUNBUFFERED=1
# echo PYTHONUNBUFFERED=$PYTHONUNBUFFERED
# export NCCL_LAUNCH_MODE=PARALLEL
# echo NCCL_LAUNCH_MODE=$NCCL_LAUNCH_MODE
# export NCCL_DEBUG=INFO
# export ONEFLOW_DEBUG_MODE=True


CUDA_VISIBLE_DEVICES='7' python train.py configs/ms1mv3_r50.py