data:
  name: aishell
  dataset_type: text
  vocab: egs/aishell/data/vocab
  batch_size: 16
  src_vocab: egs/aishell/data/vocab
  tgt_vocab: egs/aishell/data/vocab
  train:
    src: ['egs/aishell/data/train/text']
    tgt: ['egs/aishell/data/train/text']
model:
  type: rnn_lm
  vocab_size: 4233
  num_layers: 2
  hidden_size: 1024
  residual_dropout: 0.1
  smoothing: 0.1
  dropout: 0.1
  share_embedding: True
train:
  optimizer_type: adam
  optimizer:
    lr: 0.001
    betas: [0.9, 0.98]
    eps: 1.0e-9
    weight_decay: 1.0e-6
    amsgrad: False
  scheduler_type: step-linear
  scheduler:
    final_step: 100000
    start_lr: 1.0e-3
    final_lr: 1.0e-6
  clip_grad: 5
  epochs: 60
  accum_steps: 4
  grad_noise: 0.0
  load_model: False
  save_name: rnn_lm_baseline